//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Web.Services;


namespace PFL_CRM.Student_Registration
{
    public partial class InProcessStudents : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (HttpContext.Current.Session["Role"] != null)
            {
                int role = (int)HttpContext.Current.Session["Role"];

                if (role != null)
                {
                    // Step 2: Check the "Role" session value
                    if (role !=1 && role != 7 && role != 4)
                    {
                        // Redirect to the dashboard or another page
                        Response.Redirect("/Student_Registration/Dashboard.aspx");
                    }
                }
            }
            else
            {
                Response.Redirect("/Login.aspx");
            }

            // Email
            //System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
            ////create the mail message 
            //MailMessage mail = new MailMessage();

            ////set the addresses 
            //mail.From = new MailAddress("postmaster@yourdomain.com"); //IMPORTANT: This must be same as your smtp authentication address.
            //mail.To.Add("postmaster@yourdomain.com");

            ////set the content 
            //mail.Subject = "This is an email";
            //mail.Body = "This is from system.net.mail using C sharp with smtp authentication.";
            ////send the message 
            //SmtpClient smtp = new SmtpClient("mail.yourdomain.com");

            ////IMPORANT:  Your smtp login email MUST be same as your FROM address. 
            //NetworkCredential Credentials = new NetworkCredential("postmaster@yourdomain.com", "password");
            //smtp.UseDefaultCredentials = false;
            //smtp.Credentials = Credentials;
            //smtp.Port = 25;    //alternative port number is 8889
            //smtp.EnableSsl = false;
            //try
            //{
            //    smtp.Send(mail);
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine($"Email sending failed: {ex.Message}");
            //}
            
        }
        public static List<Dictionary<string, object>> DT_to_DictionaryList(DataTable dt)
        {
            List<Dictionary<string, object>> rows = new List<Dictionary<string, object>>();
            Dictionary<string, object> row;
            foreach (DataRow dr in dt.Rows)
            {
                row = new Dictionary<string, object>();
                foreach (DataColumn col in dt.Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            return rows;
        }

        [WebMethod]
        public static List<Dictionary<string, object>> GET_APPLIEDUNIVERSITIES(string id)
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.GET_APPLIED_UNIVERSITIES(id);
            return DT_to_DictionaryList(items);
        }

        [WebMethod]
        public static List<Dictionary<string, object>> Get_InProcessStatuses(string StdId,string UniId)
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.Get_InProcessStatuses(StdId,UniId);
            return DT_to_DictionaryList(items);
        }
        [WebMethod]
        public static List<Dictionary<string, object>> GET_InProcessMasterStatuses(string id,string UniId)
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.GET_InProcessMasterStatuses(id,UniId);
            return DT_to_DictionaryList(items);
        }
        [WebMethod]
        public static List<Dictionary<string, object>> GetPassportED(string ID)
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.GetPassportED(ID);
            return DT_to_DictionaryList(items);
        }
        [WebMethod]
        public static List<Dictionary<string, object>> Get_InProcessStudents()
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.GET_LIVE_STUDENTS_InProcess();
            return DT_to_DictionaryList(items);
        }

        [WebMethod]
        public static List<Dictionary<string, object>> InProcessStatusUpdate(string ID,string UniId,string Status, string Comments,
            string appId, string studId,string Fees,string Scholarship,string OAdate,string CASDeadline,string Fullfilment,string IntakeSem,
            string IntakeYear,string TravelDate,string GVisaDate,string VisaNo,string CASNo,string AmountP,string PRNo,string PDate,string CourseSD
            , string CourseED)
        {
            Std_Registration std = new Std_Registration();
            DataTable items = std.InProcessStudent_StatusUpdate(ID, UniId, Status, Comments, appId,studId,Fees,Scholarship,OAdate,CASDeadline,
                Fullfilment, IntakeSem, IntakeYear,TravelDate,GVisaDate,VisaNo,CASNo,AmountP,PRNo,PDate,CourseSD,CourseED);
            return DT_to_DictionaryList(items);
        }
    }
}
